---
# Infrastructure handlers
- name: Restart traefik
  community.docker.docker_compose_v2:
    project_src: "{{ container_data_root }}/traefik"
    state: restarted

- name: Restart crowdsec
  community.docker.docker_compose_v2:
    project_src: "{{ container_data_root }}/crowdsec"
    state: restarted

- name: Restart portainer
  community.docker.docker_compose_v2:
    project_src: "{{ container_data_root }}/portainer"
    state: restarted

- name: Restart homepage
  community.docker.docker_compose_v2:
    project_src: "{{ container_data_root }}/homepage"
    state: restarted

# Application handlers
- name: Restart radarr
  community.docker.docker_compose_v2:
    project_src: "{{ container_data_root }}/radarr"
    state: restarted

- name: Restart sonarr
  community.docker.docker_compose_v2:
    project_src: "{{ container_data_root }}/sonarr"
    state: restarted

- name: Restart booklore
  community.docker.docker_compose_v2:
    project_src: "{{ container_data_root }}/booklore"
    state: restarted
