http:
  routers:
    jellyfin:
      rule: "Host(`jellyfin.silentijsje.com`)"
      service: jellyfin
      entryPoints:
        - secureweb
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers@file
        - traefik-bouncer@file
    jellyfin2:
      rule: "Host(`jellyfin2.silentijsje.com`)"
      service: jellyfin2
      entryPoints:
        - secureweb
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers@file
        - traefik-bouncer@file
    paperless:
      rule: "Host(`paperless.silentijsje.com`)"
      service: paperless
      entryPoints:
        - secureweb
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers@file
        - traefik-bouncer@file
    immich:
      rule: "Host(`immich.silentijsje.com`)"
      service: immich
      entryPoints:
        - secureweb
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers@file
        - traefik-bouncer@file
    truenas:
      rule: "Host(`truenas.silentijsje.com`)"
      service: truenas
      entryPoints:
        - secureweb
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers@file
        - traefik-bouncer@file
        - ipAllowList@file
    pihole:
      rule: "Host(`pihole.silentijsje.com`)"
      service: pihole
      entryPoints:
        - secureweb
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers@file
        - traefik-bouncer@file
        - ipAllowList@file
    pve1:
      rule: "Host(`pve1.silentijsje.com`)"
      service: pve1
      entryPoints:
        - secureweb
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers@file
        - traefik-bouncer@file
        - ipAllowList@file
    pve2:
      rule: "Host(`pve2.silentijsje.com`)"
      service: pve2
      entryPoints:
        - secureweb
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers@file
        - traefik-bouncer@file
        - ipAllowList@file
    pbs:
      rule: "Host(`pbs.silentijsje.com`)"
      service: pbs
      entryPoints:
        - secureweb
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers@file
        - traefik-bouncer@file
        - ipAllowList@file
    unifi:
      rule: "Host(`unifi.silentijsje.com`)"
      service: unifi
      entryPoints:
        - secureweb
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers@file
        - traefik-bouncer@file
        - ipAllowList@file
    overseerr:
      rule: "Host(`overseerr.silentijsje.com`)"
      service: overseerr
      entryPoints:
        - secureweb
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers@file
        - traefik-bouncer@file
    ldap:
      rule: "Host(`ldap.silentijsje.com`)"
      service: ldap
      entryPoints:
        - secureweb
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers@file
        - traefik-bouncer@file
        - ipAllowList@file
    sonarr:
      rule: "Host(`sonarr.silentijsje.com`)"
      service: sonarr
      entryPoints:
        - secureweb
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers@file
        - traefik-bouncer@file
        - ipAllowList@file
    radarr:
      rule: "Host(`radarr.silentijsje.com`)"
      service: radarr
      entryPoints:
        - secureweb
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers@file
        - traefik-bouncer@file
        - ipAllowList@file
    qbt:
      rule: "Host(`qbt.silentijsje.com`)"
      service: qbt
      entryPoints:
        - secureweb
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers@file
        - traefik-bouncer@file
        - ipAllowList@file
    nzb:
      rule: "Host(`nzb.silentijsje.com`)"
      service: nzb
      entryPoints:
        - secureweb
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers@file
        - traefik-bouncer@file
        - ipAllowList@file
    portainer:
      rule: "Host(`portainer.silentijsje.com`)"
      service: portainer
      entryPoints:
        - secureweb
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers@file
        - traefik-bouncer@file
        - ipAllowList@file
    wizarr:
      rule: "Host(`wizarr.silentijsje.com`)"
      service: wizarr
      entryPoints:
        - secureweb
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers@file
        - traefik-bouncer@file
        - ipAllowList@file
    tautulli:
      rule: "Host(`tautulli.silentijsje.com`)"
      service: tautulli
      entryPoints:
        - secureweb
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers@file
        - traefik-bouncer@file
        - ipAllowList@file
    booklore:
      rule: "Host(`booklore.silentijsje.com`)"
      service: booklore
      entryPoints:
        - secureweb
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers@file
        - traefik-bouncer@file
        - ipAllowList@file
    mealie:
      rule: "Host(`mealie.silentijsje.com`)"
      service: mealie
      entryPoints:
        - secureweb
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers@file
        - traefik-bouncer@file
        - ipAllowList@file

  services:
    jellyfin:
      loadBalancer:
        servers:
          - url: "http://10.0.20.85:8096"
        passHostHeader: true
        serversTransport: insecure-no-verify
    jellyfin2:
      loadBalancer:
        servers:
          - url: "http://10.0.20.91:8096"
        passHostHeader: true
        serversTransport: insecure-no-verify
    immich:
      loadBalancer:
        servers:
          - url: "http://10.0.0.81:2283"
        passHostHeader: true
        serversTransport: insecure-no-verify
    truenas:
      loadBalancer:
        servers:
          - url: "http://10.0.0.2"
        passHostHeader: true
        serversTransport: insecure-no-verify
    pihole:
      loadBalancer:
        servers:
          - url: "http://10.0.0.50"
        passHostHeader: true
        serversTransport: insecure-no-verify
    pve1:
      loadBalancer:
        servers:
          - url: "https://10.0.0.70:8006"
        passHostHeader: true
        serversTransport: insecure-no-verify
    pve2:
      loadBalancer:
        servers:
          - url: "https://10.0.0.71:8006"
        passHostHeader: true
        serversTransport: insecure-no-verify
    pbs:
      loadBalancer:
        servers:
          - url: "https://10.0.0.75:8007"
        passHostHeader: true
        serversTransport: insecure-no-verify
    unifi:
      loadBalancer:
        servers:
          - url: "https://10.0.0.1"
        passHostHeader: true
        serversTransport: insecure-no-verify
    overseerr:
      loadBalancer:
        servers:
          - url: "http://10.0.0.80:5055"
        passHostHeader: true
        serversTransport: insecure-no-verify
    ldap:
      loadBalancer:
        servers:
          - url: "http://10.0.0.80:17170"
        passHostHeader: true
        serversTransport: insecure-no-verify
    sonarr:
      loadBalancer:
        servers:
          - url: "http://10.0.0.80:8989"
        passHostHeader: true
        serversTransport: insecure-no-verify
    radarr:
      loadBalancer:
        servers:
          - url: "http://10.0.0.80:7878"
        passHostHeader: true
        serversTransport: insecure-no-verify
    portainer:
      loadBalancer:
        servers:
          - url: "http://10.0.0.80:9000"
        passHostHeader: true
        serversTransport: insecure-no-verify
    paperless:
      loadBalancer:
        servers:
          - url: "http://10.0.0.80:3000"
        passHostHeader: true
        serversTransport: insecure-no-verify
    qbt:
      loadBalancer:
        servers:
          - url: "http://10.0.0.89:8090"
        passHostHeader: true
        serversTransport: insecure-no-verify
    nzb:
      loadBalancer:
        servers:
          - url: "http://10.0.0.88:7777"
        passHostHeader: true
        serversTransport: insecure-no-verify
    wizarr:
      loadBalancer:
        servers:
          - url: "http://10.0.0.80:5690"
        passHostHeader: true
        serversTransport: insecure-no-verify
    tautulli:
      loadBalancer:
        servers:
          - url: "http://10.0.0.80:8181"
        passHostHeader: true
        serversTransport: insecure-no-verify
    booklore:
      loadBalancer:
        servers:
          - url: "http://10.0.0.80:6060"
        passHostHeader: true
        serversTransport: insecure-no-verify
    mealie:
      loadBalancer:
        servers:
          - url: "http://10.0.0.80:9925"
        passHostHeader: true
        serversTransport: insecure-no-verify

  serversTransports:
    insecure-no-verify:
      insecureSkipVerify: true
